### PR TITLE
add ru lang

### PR DESCRIPTION
**Pull request by legiz-ru**
If there is anything else that needs to be added, please let me know

### CODE REVIEW

**Comment by Zephyruso** [comment]
I made some changes, Try to see if it works as expected

**Comment by Zephyruso** [comment]
image
Are there any suitable abbreviations?

**Comment by legiz-ru** [comment]
> Are there any suitable abbreviations?

@Zephyruso yes, i will check all new injections, and create new pull

**Comment by Zephyruso** [comment]
I used abbreviations from ChatGPT, but I'm not sure whether they are accurate
image

**Pull request merged**
